### ISSUE TITLE
some testsuites hanging with tasty?

### ISSUE THREAD

**Issue by juhp** [feuerbach/tasty#266] opened 2020-02-21 14:26 UTC
After updating Fedora to tasty-1.2.3 (basically LTS 14) testsuites using tasty seem to hang now.
I haven't invested further - I probably will look into it more later when I have time.
But thought I would ask here first in case this is a known issue or rings any bells.

**Comment by feuerbach** [comment] 2020-02-21 14:35
Ugh, that sounds bad. Do you have an example?

**Comment by feuerbach** [comment] 2020-02-21 14:38
tasty-1.2.3 was released more than 6 months ago, so if there was a serious bug affecting multiple test suites, I think someone would've noticed...

Do those test suite also use tasty-golden, which was being updated in the past couple of days?

**Comment by feuerbach** [comment] 2020-02-21 14:42
And LTS 14.0 was released in August, and IIRC they run all the test suites for (almost) all packages, so people would definitely notice if several test suites stopped working there.

Is this consistently reproducible? How many/which packages are affected?

**Comment by juhp** [comment] 2020-03-01 11:20
I think Fedora 32 is pretty close to final lts-14 - ie lts-14.26 or so.

> Do those test suite also use tasty-golden, which was being updated in the past couple of days?

No tasty-golden is not in Fedora (yet anyway).

> Is this consistently reproducible?

Yes.
It is quite surprising and unexpected to me

> How many/which packages are affected?

I am not exactly sure (because some packages do have tests disabled) but around 30-40 packages probably.

Any suggestions for how to debug this?

**Comment by sjakobi** [comment] 2020-03-01 11:25
Could there be a relation to this GHC ticket? https://gitlab.haskell.org/ghc/ghc/issues/17744

**Comment by juhp** [comment] 2020-03-01 13:59
Thanks @sjakobi that sounds it could well be the problem: I think part of it was that I tried to enable more testsuites for Fedora 32, which lead me to notice this. I suppose one could pass -O0 via `cabal test` to workaround this too.

**Comment by feuerbach** [comment] 2020-03-01 14:10
Probably not a coincidence—the example on the ghc bug tracker also involves tasty. So let's keep this open until we figure out what's going on.

**Comment by feuerbach** [comment] 2020-03-01 14:33
Ah, I see that Mario's latest [reproducible example](https://gitlab.haskell.org/ghc/ghc/issues/17744#note_250014) does not depend on tasty at all. (And I also verified that it doesn't depend on being in a Cabal test suite—a simple executable hangs as well.)

@juhp could you please confirm that -O0 fixes the failures you observe, so that we can be reasonably sure it's the same bug?

**Comment by juhp** [comment] 2020-03-05 11:18
> (And I also verified that it doesn't depend on being in a Cabal test suite—a simple executable hangs as well.)

Is that mentioned explicitly in the ghc issue?  (It might well be implied.)

> @juhp could you please confirm that -O0 fixes the failures you observe, so that we can be reasonably sure it's the same bug?

I can confirm -O0 fixes the testsuite hang for cryptonite-0.25 for me.
(The problem doesn't affect all packages, eg x509-1.7.5 testsuite works for both -O1 and -O0.)
I will try to do some more tests, but I reckon this can be closed now.

**Comment by sjakobi** [comment] 2020-03-05 15:40
@juhp Could you report in that GHC issue which testsuites you observed to hang?

It seems to me that it hasn't been understood so far how widespread that hanging issue is.

**Comment by juhp** [comment] 2020-06-03 11:12
Sorry for not getting back on this: I had wanted to provide a complete list of Fedora packages affecting but didn't find time for that yet.

One example is test-cryptonite in cryptonite-0.25 - as I work out on updating for Fedora 33 I will check for more (cryptonite is also rather big).

**Comment by feuerbach** [comment] 2020-06-15 18:57
Looks like the issue has been confirmed and fixed in ghc, closing.

**Closed by feuerbach** 2020-06-15 18:57 UTC
